#!/bin/bash
PKG_PATH=${PKG_PATH:-/home/pkgs};
[ "$1" = "clean" ] && {
    apt-get $1;
    find -L $PKG_PATH/bin -wholename $PKG_PATH/bin -o -type d -prune -o -type l -exec rm {} +;
    find -L $PKG_PATH/lib -wholename $PKG_PATH/lib -o -type d -prune -o -type l -exec rm {} +;
    exit 0;
}
[[ "$1" = "install" || "$1" = "crack" ]] && {
    op="install";
    if [[ "$1" = "crack" ]]; then
	    dir="$HOME/packages/$2";
    else
	    dir="$PKG_PATH";
    fi
    [ "$1" = "install" ] && {
            [ -d "$PKG_PATH" ] || { echo "$PKG_PATH does not exist, please run crackle setup first"; exit 1; }
    }
    apt-get update;
    apt-get -y "$op" --download-only "$2":${ARCH} || exit 1;
    readarray -t packages < <(ls /var/cache/apt/archives/*.deb);
    for package in "${packages[@]}"
        do
            dpkg-deb -xv "$package" "$dir";
        done;
}
